# Generated by Django 5.0.3 on 2026-07-07 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('period_type', models.CharField(choices=[('annual', 'Annual'), ('half_year', 'Half Year')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_audited', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['end_date'],
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_operating_cash', models.DecimalField(decimal_places=2, max_digits=12)),
                ('depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('working_capital_movement', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_investing_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_financing_cash', models.DecimalField(decimal_places=2, max_digits=12)),
                ('equity_raised', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loans_net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_cash_movement', models.DecimalField(decimal_places=2, max_digits=12)),
                ('opening_cash', models.DecimalField(decimal_places=2, max_digits=12)),
                ('closing_cash', models.DecimalField(decimal_places=2, max_digits=12)),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flow', to='board.financialperiod')),
            ],
            options={
                'ordering': ['period__end_date'],
            },
        ),
        migrations.CreateModel(
            name='BusinessMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_customers', models.IntegerField(blank=True, null=True)),
                ('enterprise_customers', models.IntegerField(blank=True, null=True)),
                ('acv_soil_per_enterprise', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('acv_era_per_enterprise', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('revenue_ireland_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('pipeline_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pipeline_deals_count', models.IntegerField(blank=True, null=True)),
                ('employees', models.IntegerField(blank=True, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('share_price', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_metrics', to='board.financialperiod')),
            ],
            options={
                'ordering': ['period__end_date'],
            },
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodwill', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('development_costs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tangible_assets', models.DecimalField(decimal_places=2, max_digits=12)),
                ('debtors', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_creditors', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contingent_consideration', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('long_term_debt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('share_capital', models.DecimalField(decimal_places=2, max_digits=12)),
                ('share_premium', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('retained_earnings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance_sheet', to='board.financialperiod')),
            ],
            options={
                'ordering': ['period__end_date'],
            },
        ),
        migrations.CreateModel(
            name='PLStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_of_sales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('distribution_costs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('admin_expenses', models.DecimalField(decimal_places=2, max_digits=12)),
                ('other_operating_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interest_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('operating_loss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loss_before_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loss_after_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pl_statement', to='board.financialperiod')),
            ],
            options={
                'ordering': ['period__end_date'],
            },
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('executive_summary', 'Executive Summary'), ('revenue_growth', 'Revenue & Growth'), ('profitability', 'Profitability'), ('cash_liquidity', 'Cash & Liquidity'), ('solvency_leverage', 'Solvency & Leverage'), ('returns', 'Returns'), ('outlook', 'Outlook & Strategy')], max_length=30)),
                ('generated_text', models.TextField()),
                ('model_used', models.CharField(default='gemini-1.5-flash', max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='board.financialperiod')),
            ],
            options={
                'ordering': ['-generated_at'],
                'unique_together': {('period', 'section')},
            },
        ),
    ]
