# Generated by Django 5.0.3 on 2026-07-07 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_kind', models.CharField(choices=[('pl_statement', 'P&L Statement'), ('balance_sheet', 'Balance Sheet'), ('cash_flow', 'Cash Flow'), ('business_metrics', 'Business Metrics')], max_length=30)),
                ('source_document', models.CharField(help_text='Filename or path of the source PDF', max_length=255)),
                ('model_used', models.CharField(default='gemini-1.5-flash', max_length=50)),
                ('raw_response', models.JSONField(blank=True, help_text='Raw JSON returned by Gemini', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('schema_valid', 'Schema Valid'), ('schema_invalid', 'Schema Invalid'), ('cross_check_pass', 'Cross-Check Pass'), ('cross_check_fail', 'Cross-Check Fail'), ('api_error', 'API Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('cross_check_results', models.JSONField(blank=True, null=True)),
                ('match_rate_pct', models.DecimalField(blank=True, decimal_places=1, help_text='Percentage of fields that matched ground truth within tolerance', max_digits=5, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_attempts', to='board.financialperiod')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
