# Generated by Django 5.0.3 on 2026-07-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_extractionattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinsight',
            name='model_used',
            field=models.CharField(default='gemini-2.5-flash', max_length=50),
        ),
    ]
