# Generated by Django 5.0.3 on 2026-07-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_aiinsight_model_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinsight',
            name='source_data_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
