# Generated by Django 5.0.3 on 2026-07-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_aiinsight_source_data_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionattempt',
            name='source_content_hash',
            field=models.CharField(blank=True, help_text='SHA-256 of the source PDF bytes, used to skip re-calling Gemini when the same document is re-run against the same period/kind', max_length=64),
        ),
    ]
