# Generated by Django 5.0.3 on 2026-07-11 18:12

from django.db import migrations

# Matches the GOOGLE_ALLOWED_EMAILS env var this table replaces — without
# this seed, GoogleLoginView switching from the env var to this table
# would lock out everyone currently allowed to sign in.
SEED_EMAILS = [
    "eoinmccormack420@gmail.com",
    "Barry@assiduous.tech",
    "Fergal@assiduous.tech",
    "Aniij@assiduous.tech",
]


def seed_emails(apps, schema_editor):
    AllowedGoogleEmail = apps.get_model("board", "AllowedGoogleEmail")
    for email in SEED_EMAILS:
        AllowedGoogleEmail.objects.get_or_create(email=email)


def remove_seeded_emails(apps, schema_editor):
    AllowedGoogleEmail = apps.get_model("board", "AllowedGoogleEmail")
    AllowedGoogleEmail.objects.filter(email__in=SEED_EMAILS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_allowedgoogleemail_userpreferences'),
    ]

    operations = [
        migrations.RunPython(seed_emails, remove_seeded_emails),
    ]
