# Generated by Django 5.0.3 on 2026-07-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_seed_allowed_google_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_webhook_url', models.URLField(blank=True)),
                ('teams_webhook_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
