# Generated by Django 5.0.3 on 2026-07-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_notificationsettings_from_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='gmail_connected_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='gmail_refresh_token',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
