# Generated by Django 5.0.3 on 2026-07-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_notificationsettings_gmail_connected_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardAlertSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_runway_enabled', models.BooleanField(default=True)),
                ('cash_runway_months_min', models.DecimalField(decimal_places=1, default=12, max_digits=5)),
                ('ebitda_margin_enabled', models.BooleanField(default=True)),
                ('ebitda_margin_min_pct', models.DecimalField(decimal_places=1, default=-25, max_digits=5)),
                ('admin_expense_ratio_enabled', models.BooleanField(default=True)),
                ('admin_expense_ratio_max_pct', models.DecimalField(decimal_places=1, default=100, max_digits=5)),
                ('current_ratio_enabled', models.BooleanField(default=True)),
                ('current_ratio_min', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notify_on_board_alerts',
            field=models.BooleanField(default=False),
        ),
    ]
