# Generated by Django 5.0.3 on 2026-07-13 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_boardalertsettings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisoryGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('rationale', models.TextField()),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('committed', 'Committed'), ('completed', 'Completed'), ('dismissed', 'Dismissed')], default='suggested', max_length=20)),
                ('model_used', models.CharField(blank=True, max_length=50)),
                ('source_data_hash', models.CharField(blank=True, max_length=64)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('committed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisory_goals', to='board.financialperiod')),
            ],
            options={
                'ordering': ['period__end_date', 'order'],
            },
        ),
    ]
