# Generated by Django 5.0.3 on 2026-07-13 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_seed_ecosystem_checklist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('audience_label', models.CharField(max_length=200)),
                ('context_note', models.TextField(blank=True)),
                ('include_revenue_growth', models.BooleanField(default=True)),
                ('include_profitability', models.BooleanField(default=True)),
                ('include_cash_liquidity', models.BooleanField(default=True)),
                ('include_solvency_leverage', models.BooleanField(default=True)),
                ('include_returns', models.BooleanField(default=True)),
                ('include_outlook', models.BooleanField(default=True)),
                ('use_tailored_narrative', models.BooleanField(default=False)),
                ('tailored_narrative', models.JSONField(blank=True, null=True)),
                ('narrative_model_used', models.CharField(blank=True, max_length=50)),
                ('narrative_source_hash', models.CharField(blank=True, max_length=64)),
                ('narrative_generated_at', models.DateTimeField(blank=True, null=True)),
                ('narrative_approved', models.BooleanField(default=False)),
                ('narrative_approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('narrative_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_specs', to='board.financialperiod')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
