# Generated by Django 5.0.3 on 2026-07-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0017_drivesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivesettings',
            name='connected_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='drivesettings',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
