# Generated by Django 5.0.3 on 2026-07-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0018_drivesettings_connected_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivesettings',
            name='folder_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
