# Generated by Django 5.0.3 on 2026-07-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0019_drivesettings_folder_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncubatorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_location', models.CharField(default='Dublin, Ireland', max_length=255)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('last_refresh_error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NearbyIncubator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('website', models.URLField(blank=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('maps_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-rating', 'name'],
            },
        ),
    ]
