# Generated by Django 5.0.3 on 2026-07-14 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0020_incubatorsettings_nearbyincubator'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingRoadmapStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('timeframe', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('model_used', models.CharField(blank=True, max_length=50)),
                ('source_data_hash', models.CharField(blank=True, max_length=64)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_roadmap_steps', to='board.financialperiod')),
            ],
            options={
                'ordering': ['period__end_date', 'order'],
            },
        ),
    ]
