# Generated by Django 5.0.3 on 2026-07-14 11:47

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


def create_vector_extension(apps, schema_editor):
    # Postgres-only: the vector(1536) column type in the CreateModel
    # below doesn't exist until the pgvector extension is installed, so
    # this must run first. On SQLite this is a no-op — SQLite's type
    # affinity happily stores the column as text and similarity search
    # falls back to Python (see board/extraction/retrieval.py).
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS vector;")


def create_hnsw_index(apps, schema_editor):
    # HNSW is a pgvector access method — Postgres-only, hence not in
    # Meta.indexes (which would break SQLite migrate/pytest).
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            "CREATE INDEX IF NOT EXISTS board_vectordocumentchunk_embedding_hnsw "
            "ON board_vectordocumentchunk "
            "USING hnsw (embedding vector_cosine_ops) "
            "WITH (m = 16, ef_construction = 64);"
        )


def drop_hnsw_index(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("DROP INDEX IF EXISTS board_vectordocumentchunk_embedding_hnsw;")


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0021_fundingroadmapstep'),
    ]

    operations = [
        migrations.RunPython(create_vector_extension, migrations.RunPython.noop),
        migrations.CreateModel(
            name='VectorDocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_kind', models.CharField(blank=True, choices=[('pl_statement', 'P&L Statement'), ('balance_sheet', 'Balance Sheet'), ('cash_flow', 'Cash Flow'), ('business_metrics', 'Business Metrics')], max_length=20)),
                ('source_document', models.CharField(max_length=500)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('chunk_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('embedding_model', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_chunks', to='board.financialperiod')),
            ],
            options={
                'ordering': ['source_document', 'chunk_index'],
                'unique_together': {('source_document', 'chunk_index')},
            },
        ),
        migrations.CreateModel(
            name='KnowledgeGraphNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('euronext_rule', 'Euronext Rule'), ('ei_benchmark', 'EI Benchmark'), ('subsidiary', 'Subsidiary Company'), ('regulator', 'Regulator'), ('requirement', 'Requirement'), ('other', 'Other')], max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graph_nodes', to='board.vectordocumentchunk')),
            ],
            options={
                'ordering': ['node_type', 'name'],
                'unique_together': {('node_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='KnowledgeGraphEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_type', models.CharField(choices=[('COMPLIES_WITH', 'Complies with'), ('PARENT_OF', 'Parent of'), ('REQUIRES_AUDIT_YEARS', 'Requires audit years'), ('REQUIRES', 'Requires'), ('GOVERNED_BY', 'Governed by'), ('RELATED_TO', 'Related to')], max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='board.knowledgegraphnode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='board.knowledgegraphnode')),
            ],
            options={
                'unique_together': {('source', 'target', 'edge_type')},
            },
        ),
        migrations.RunPython(create_hnsw_index, drop_hnsw_index),
    ]
