# Generated by Django 5.0.3 on 2026-07-14 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0022_vectordocumentchunk_knowledgegraphnode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('context_chunks', models.JSONField(blank=True, default=list)),
                ('figures_snapshot', models.JSONField(blank=True, default=dict)),
                ('graph_triples', models.JSONField(blank=True, default=list)),
                ('model_used', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_questions', to='board.financialperiod')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
