"""
Tests for report_deck.py's generate_deck: real python-pptx generation
(pure Python, no browser/mocking needed, fast) — asserts on slide count
and rendered text content by reopening the generated bytes with
python-pptx's own Presentation() reader.
"""

import io
from datetime import date
from decimal import Decimal

import pytest
from pptx import Presentation

from board.extraction.report_deck import generate_deck
from board.models import BalanceSheet, CashFlow, FinancialPeriod, PLStatement, ReportSpec


def make_period(label="TEST", **kwargs):
    defaults = dict(period_type="half_year", start_date=date(2025, 1, 1), end_date=date(2025, 6, 30))
    defaults.update(kwargs)
    return FinancialPeriod.objects.create(label=label, **defaults)


def make_pl_statement(period, **kwargs):
    defaults = dict(
        revenue=Decimal("100000"), cost_of_sales=Decimal("20000"), admin_expenses=Decimal("30000"),
        gross_profit=Decimal("80000"), operating_loss=Decimal("-10000"),
        loss_before_tax=Decimal("-10000"), loss_after_tax=Decimal("-10000"),
    )
    defaults.update(kwargs)
    return PLStatement.objects.create(period=period, **defaults)


def make_balance_sheet(period, **kwargs):
    defaults = dict(
        tangible_assets=Decimal("50000"), debtors=Decimal("10000"), cash=Decimal("20000"),
        current_creditors=Decimal("-15000"), share_capital=Decimal("1000"), retained_earnings=Decimal("-5000"),
    )
    defaults.update(kwargs)
    return BalanceSheet.objects.create(period=period, **defaults)


def make_cash_flow(period, **kwargs):
    defaults = dict(
        net_operating_cash=Decimal("-5000"), net_financing_cash=Decimal("2000"),
        net_cash_movement=Decimal("-3000"), opening_cash=Decimal("23000"), closing_cash=Decimal("20000"),
    )
    defaults.update(kwargs)
    return CashFlow.objects.create(period=period, **defaults)


def make_full_period(label="TEST"):
    period = make_period(label=label)
    make_pl_statement(period)
    make_balance_sheet(period)
    make_cash_flow(period)
    return period


def make_spec(period, **kwargs):
    defaults = dict(audience_label="Series A Investors", context_note="Fundraising round")
    defaults.update(kwargs)
    return ReportSpec.objects.create(period=period, **defaults)


def all_text(prs: Presentation) -> str:
    chunks = []
    for slide in prs.slides:
        for shape in slide.shapes:
            if shape.has_text_frame:
                chunks.append(shape.text_frame.text)
    return "\n".join(chunks)


@pytest.mark.django_db
class TestGenerateDeck:
    def test_returns_a_valid_presentation(self):
        period = make_full_period()
        spec = make_spec(period)

        deck_bytes = generate_deck(spec)
        prs = Presentation(io.BytesIO(deck_bytes))

        assert len(prs.slides) == 7  # title + 6 sections (all included by default)

    def test_title_slide_shows_audience_and_context(self):
        period = make_full_period()
        spec = make_spec(period, audience_label="Bank of Ireland", context_note="Loan renewal discussion")

        prs = Presentation(io.BytesIO(generate_deck(spec)))

        text = all_text(prs)
        assert "Bank of Ireland" in text
        assert "Loan renewal discussion" in text

    def test_excluded_sections_produce_fewer_slides(self):
        period = make_full_period()
        spec = make_spec(period, include_returns=False, include_outlook=False)

        prs = Presentation(io.BytesIO(generate_deck(spec)))

        assert len(prs.slides) == 5  # title + 4 remaining sections
        text = all_text(prs)
        assert "Returns" not in text
        assert "Outlook" not in text

    def test_stat_values_are_rendered(self):
        period = make_full_period()
        spec = make_spec(period)

        text = all_text(Presentation(io.BytesIO(generate_deck(spec))))

        # revenue=100000 -> "€100,000" per _format_value's eur formatting
        assert "€100,000" in text

    def test_no_narrative_bullets_when_not_approved(self):
        period = make_full_period()
        spec = make_spec(
            period,
            use_tailored_narrative=True,
            tailored_narrative={"revenue_growth": "This should not appear anywhere in the deck."},
            narrative_approved=False,
        )

        text = all_text(Presentation(io.BytesIO(generate_deck(spec))))

        assert "This should not appear anywhere in the deck." not in text

    def test_narrative_bullets_appear_once_approved(self):
        period = make_full_period()
        spec = make_spec(
            period,
            use_tailored_narrative=True,
            tailored_narrative={"revenue_growth": "Revenue grew strongly this half. Momentum continues."},
            narrative_approved=True,
        )

        text = all_text(Presentation(io.BytesIO(generate_deck(spec))))

        assert "Revenue grew strongly this half." in text
