"""
Django settings for assiduous_dash project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

import dj_database_url

from corsheaders.defaults import default_headers

# Load environment variables from .env file
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

# Places API (New) — powers the "Nearby Startup Incubators" card on
# /readiness (board/extraction/places_client.py). Requires a Google Cloud
# project with billing enabled, even for free-tier usage.
GOOGLE_PLACES_API_KEY = os.environ.get("GOOGLE_PLACES_API_KEY", "")

# Google Sign-In (see board/views.py:GoogleLoginView). GOOGLE_ALLOWED_EMAILS
# is a hard allowlist — a verified Google ID token alone is not enough to
# log in, the email must also be in this list, since this app serves
# unreleased financial data to a small fixed set of reviewers rather than
# the public.
GOOGLE_OAUTH_CLIENT_ID = os.environ.get("GOOGLE_OAUTH_CLIENT_ID", "")
GOOGLE_ALLOWED_EMAILS = {
    e.strip().lower()
    for e in os.environ.get("GOOGLE_ALLOWED_EMAILS", "").split(",")
    if e.strip()
}

# Needed only for the "Connect Gmail" notification flow (see
# board/extraction/gmail_oauth.py) — exchanging an authorization code
# for a refresh token requires the OAuth client's secret, unlike the
# ID-token verification GoogleLoginView does above. Get this from the
# same OAuth 2.0 Client ID's page in Google Cloud Console.
GOOGLE_OAUTH_CLIENT_SECRET = os.environ.get("GOOGLE_OAUTH_CLIENT_SECRET", "")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# This literal is only ever used as the local-dev fallback — see the
# env-driven SECRET_KEY assignment below, which overrides it whenever
# a real SECRET_KEY env var is set (production).
SECRET_KEY = 'django-insecure-eu0u1yn=(h+wt%yn*gx4v#1@hv92&anqo_)9l-+a077wyjh8nz'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'board',
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'assiduous_dash.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

WSGI_APPLICATION = 'assiduous_dash.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images) — STATIC_URL/STATIC_ROOT/STORAGES
# are set below (production config block), alongside WhiteNoise.
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


DEBUG = os.environ.get("DEBUG", "False") == "True"
 
SECRET_KEY = os.environ.get("SECRET_KEY", SECRET_KEY)  # keep your existing dev fallback
 
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
 
# Railway sets DATABASE_URL automatically once you add a Postgres plugin
DATABASE_URL = os.environ.get("DATABASE_URL")
if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
 
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Single-service deployment: the React build is served directly by
# WhiteNoise at the site root, separate from Django's own /static/ app
# assets above. WHITENOISE_ROOT exists exactly for this — serving a
# whole extra directory of files at the root — which matters here
# because Vite's build references its own assets as root-relative
# ("/assets/...", "/favicon.svg"), not "/static/..."-prefixed, so it
# has to be a distinct mechanism from STATIC_ROOT rather than folded
# into it.
#
# This lives INSIDE assiduous_dash/ (built there directly by Vite's
# outDir config, not senus-dashboard/dist as a sibling) because
# Railway's build for this service only packages the assiduous_dash/
# subtree — confirmed via a deploy log showing WhiteNoise couldn't
# find a sibling directory at runtime.
FRONTEND_DIST_DIR = BASE_DIR / "frontend_dist"
WHITENOISE_ROOT = FRONTEND_DIST_DIR

# CORS — FRONTEND_URL must be set to the frontend's actual Railway
# service URL (https://..., no trailing slash). Keep localhost:5173 in
# the list too, so local dev against the deployed backend still works.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    os.environ.get("FRONTEND_URL", ""),  # e.g. https://senus-dashboard.up.railway.app
]
CORS_ALLOWED_ORIGINS = [origin for origin in CORS_ALLOWED_ORIGINS if origin]
 
# Needed for the Authorization header (token auth) to pass CORS preflight
CORS_ALLOW_HEADERS = list(default_headers) + ["authorization"]
 
SECURE_SSL_REDIRECT = not DEBUG

# Email — backs UserPreferences.notify_on_new_insights (see
# board/extraction/email_notifications.py). Defaults to the console
# backend so nothing ever sends to a real inbox until EMAIL_BACKEND is
# explicitly set to Django's smtp backend in a deployment's env.
EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True") == "True"
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "Senus Board Report <noreply@senus.example>")
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# Railway (like Heroku/Render/Fly) terminates TLS at its edge and
# forwards plain HTTP internally. Without this, Django can't tell a
# proxied HTTPS request from a genuinely insecure one, so
# SECURE_SSL_REDIRECT above would redirect every request to https://
# even ones that already arrived as https:// — an infinite redirect
# loop. This tells Django to trust the standard X-Forwarded-Proto
# header Railway's edge sets.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Django's SecurityMiddleware defaults this header to "same-origin",
# which severs window.opener between our page and the popup Google
# Identity Services opens for the account picker — the popup can no
# longer postMessage the credential back once the user confirms, so
# Google Sign-In hangs right after the account-confirmation step with
# a failed request to accounts.google.com/gsi/transform in devtools.
# "same-origin-allow-popups" keeps the isolation but permits windows we
# open ourselves (like Google's) to communicate back.
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"
