// src/styles/FundingRoadmapStyles.ts
//
// Style constants extracted from src/components/FundingRoadmap.tsx.

import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  card: {
    padding: "var(--space-4)",
    marginBottom: "var(--space-4)",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "var(--space-3)",
    marginBottom: "var(--space-3)",
  },
  eyebrowRow: {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-2)",
  },
  cardIconBadge: {
    flexShrink: 0,
    width: 24,
    height: 24,
    borderRadius: "var(--radius-sm)",
    background: "var(--color-forest-soft)",
    color: "var(--color-forest)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  eyebrow: {
    fontFamily: "var(--font-body)",
    fontWeight: 600,
    fontSize: "var(--text-sm)",
    color: "var(--color-ink)",
    margin: 0,
  },
  aiBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "3px",
    fontSize: "10px",
    fontWeight: 700,
    color: "var(--color-forest)",
    background: "var(--color-forest-soft)",
    padding: "2px 7px",
    borderRadius: 999,
    letterSpacing: "0.02em",
  },
  caption: {
    fontSize: "var(--text-xs)",
    color: "var(--color-grey-text)",
    margin: "var(--space-1) 0 0 0",
  },
  generateButton: {
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    fontFamily: "var(--font-body)",
    fontSize: "var(--text-xs)",
    fontWeight: 600,
    padding: "6px 14px",
    borderRadius: "var(--radius-sm)",
    border: "none",
    background: "var(--color-forest)",
    color: "var(--color-on-accent)",
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  spinner: {
    width: 11,
    height: 11,
    borderRadius: "50%",
    border: "2px solid rgba(255,255,255,0.4)",
    borderTopColor: "#FFFFFF",
    marginRight: 6,
  },
  emptyText: {
    fontSize: "var(--text-xs)",
    color: "var(--color-grey-text)",
    margin: 0,
  },
  errorText: {
    fontSize: "var(--text-xs)",
    color: "var(--color-rust)",
    margin: "0 0 var(--space-3) 0",
  },
  timeline: {
    display: "flex",
    flexDirection: "column",
  },
  phaseRow: {
    display: "flex",
    gap: "var(--space-3)",
  },
  railColumn: {
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    width: 32,
  },
  node: {
    flexShrink: 0,
    width: 32,
    height: 32,
    borderRadius: "50%",
    background: "var(--color-forest)",
    color: "var(--color-on-accent)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "var(--font-body)",
    fontWeight: 700,
    fontSize: "var(--text-sm)",
    boxShadow: "0 0 0 4px var(--color-forest-soft)",
  },
  // The rail connector fills the gap between nodes — a fixed min-height
  // rather than 100% so a short description doesn't collapse the line
  // to nothing, and flex: 1 so it still stretches for longer cards.
  connector: {
    flex: 1,
    width: 2,
    minHeight: "var(--space-3)",
    background: "linear-gradient(var(--color-forest), var(--color-forest-soft))",
  },
  phaseCard: {
    flex: 1,
    minWidth: 0,
    background: "var(--color-paper)",
    border: "1px solid var(--color-grey-line)",
    borderRadius: "var(--radius-md)",
    padding: "var(--space-3)",
    marginBottom: "var(--space-3)",
  },
  phaseTimeframe: {
    fontFamily: "var(--font-body)",
    fontSize: "var(--text-xs)",
    fontWeight: 700,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: "var(--color-forest)",
    margin: "0 0 var(--space-1) 0",
  },
  phaseTitle: {
    fontFamily: "var(--font-display)",
    fontWeight: 600,
    fontSize: "var(--text-lg)",
    color: "var(--color-ink)",
    margin: "0 0 var(--space-2) 0",
  },
  phaseDescription: {
    fontFamily: "var(--font-body)",
    fontSize: "var(--text-sm)",
    color: "var(--color-grey-text)",
    margin: 0,
    lineHeight: 1.5,
  },
};
